// <auto-generated />
namespace Documents.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_cwid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_cwid));
        
        string IMigrationMetadata.Id
        {
            get { return "202207131108394_user_cwid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
